name: Production Style Pipeline

on:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js with Cache
        uses: actions/setup-node@v4

        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: |
          echo "Running Tests..."
          sleep 5
          echo "Tests Passed"

  lint:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js with Cache
        uses: actions/setup-node@v4

        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: |
          echo "Checking Code Quality..."
          sleep 3
          echo "Lint Passed"

  build:
    needs:
      - test
      - lint

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js with Cache
        uses: actions/setup-node@v4

        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: |
          echo "Building React Application..."
          npm run build

  # deployment job

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:

      - name: Fake Deployment
        run: |
          echo "Deploying Application..."
          sleep 5
          echo "Deployment Successful"