name: Runner Deep Practice

on:
  workflow_dispatch:

jobs:

  explore-runner:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Basic Runner Information
        run: |
          echo "Current User:"
          whoami

          echo "Current Directory:"
          pwd

          echo "Operating System:"
          uname -a
          
      - name: Environment Variables
        run: env

      - name: Check CPU and RAM
        run: |
          echo "CPU Cores:"
          nproc

          echo "RAM Information:"
          free -h

      - name: Check Installed Tools
        run: |
          echo "Git Version:"
          git --version

          echo "Node Version:"
          node --version

          echo "NPM Version:"
          npm --version

          echo "Docker Version:"
          docker --version

      - name: Show Files
        run: ls -la

  parallel-job-1:
    runs-on: ubuntu-latest

    steps:
      - name: Create File
        run: |
          echo "Hello from Job 1" > test.txt
          ls

  parallel-job-2:
    runs-on: ubuntu-latest

    steps:
      - name: Check File
        run: ls