name: Secrets Practice Workflow

on:
  push:
    branches:
      - main
      - dev

  workflow_dispatch:

env:
  APP_NAME: MyReactApp
  NODE_ENV: production

jobs:

  app-info:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print App Information
        run: |
          echo "Application Name: $APP_NAME"
          echo "Environment: $NODE_ENV"

      - name: Print Branch Name
        run: |
         echo "Current Branch: ${{ github.ref_name }}"

      - name: Print Secret Safely
        run: echo "${{ secrets.APP_PASSWORD }}"

  fake-deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_IP: 54.12.34.56
      DOCKER_IMAGE: my-react-app

    steps:

      - name: Deployment Information
        run: |
          echo "Deploying image: $DOCKER_IMAGE"
          echo "Target Server: $SERVER_IP"

      - name: Simulate AWS Login
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        run: |
          echo "Connecting to AWS..."
          echo "AWS Login Successful"

      - name: Fake Docker Commands
        run: |
          echo "docker build -t my-react-app ."
          echo "docker push my-react-app"
          echo "Deployment Completed"